# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Stephen Shao
title: Principal Software Engineer | Test Architect
email: sjh311@gmail.com
website: inkomato.github.io

# Social links
#twitter_username: facespics
github_username:  inkomato
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: stephen-shao-130253
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Stephen and I'm a Principal Software Engineer at Dell EMC, currently one of the Mid-range storage test architect.

  I am most skilled in <mark>information infrastructure technologies</mark>: Primary storage (Unity, VNX), Data protection solutions (Avamar, Datadomain). Especially good at <mark>file system testing</mark>: file access protocol, file systems and file data services. 

  I have solid test development (Python/Robot framework, Perl/Automatos) skills and CI experience.
  I am a proven tech leader on strategy making, test planning, test design & execution, etc in global projects.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Long-distance running
   - Photography
   - Travel
   - Music
   - Reading

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
