# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Stephen Shao
title: Principal Software Engineer | Test Architect
email: sjh311@gmail.com
website: inkomato.github.io

# Social links
#twitter_username: facespics
github_username:  inkomato
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: stephen-shao-130253
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Stephen and I'm a Principal Software Engineer at Dell EMC. I have 14 years SW engineering experience as both developer and QA.

  I am most skilled in: <mark>Storage</mark> and <mark>Complex System Testing</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Long-distance running
   - Photography
   - Travel
   - Reading
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
